language: node_js
node_js:
- 10.16.0
addons:
  ssh_known_hosts:
  - "$QA_SERVER"
branches:
  only:
  - master
before_install:

- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key
before_script:
- echo -e "Host $QA_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g @angular/cli
- npm install -g bower
- npm install -g firebase-tools
script:
- cd client
- npm install
- npm run build-ci
- cd ../
notifications:
  slack:
    rooms:
    - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#code
    - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#opening-pathways-dev
